---
title: "learnRvideos"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

A repository of useful links to videos for learning about R

<!---------------------------------------------------------------------------->
<!-------------------------------- GUIS -------------------------------------->
<!---------------------------------------------------------------------------->

## Interfaces

#### Rstudio

+ [Intro to RStudio](https://www.youtube.com/watch?v=8BAb0irAK2U) by Steph Locke
+ [Creating projects in Rstudio](https://www.youtube.com/watch?v=etkSsF6r2iU) by Steph Locke
+ [Using console in Rstudio](https://www.youtube.com/watch?v=2hg1Qg7uLwU) by Steph Locke
+ [Code completion in Rstudio](https://www.youtube.com/watch?v=pGOF4gTyeXA) by Steph Locke
+ [Creating new R script in Rstudio](https://www.youtube.com/watch?v=rWHV2VlQo2w) by Steph Locke
+ [Importing data into Rstudio](https://www.youtube.com/watch?v=H17CciuBp-E) by Rstudio
+ [Introducing notebooks](https://www.youtube.com/watch?v=w9GN7BqDfiE)


<!---------------------------------------------------------------------------->
<!---------------------------- DATA WRANGLING -------------------------------->
<!---------------------------------------------------------------------------->

## Data wrangling

#### Tidyverse

+ [Exploratory data analysis with tidyverse](https://www.youtube.com/watch?v=yYncj2FUO20) by Michael Levy
+ [Intro to data wrangling and the tidyverse pt 1](https://www.youtube.com/watch?v=jOd65mR1zfw) by Garret Grolemund
+ [Intro to data wrangling and the tidyverse pt 2](https://www.youtube.com/watch?v=1ELALQlO-yM) by Garret Grolemund
+ [Intro to data wrangling and the tidyverse pt 3](https://www.youtube.com/watch?v=Zc_ufg4uW4U) by Garret Grolemund
+ [Data wrangling](https://www.youtube.com/watch?v=y9KJmUGc8SE) by Rstudio
+ [Tidy data and tidyr](https://www.youtube.com/watch?v=1ELALQlO-yM) by Garret Grolemund
+ [Working with two data sets: binds and joins](https://www.youtube.com/watch?v=AuBgYDCg1Cg) by Garret Grolemund

#### sf
+ [Tidy geometries with {sf}](https://www.youtube.com/watch?v=sj1hXwbCfoc)

#### glue
+ [Overview of {glue} package](https://www.youtube.com/watch?v=vX8iWTBfGgg) by Jim Hester

##### broom

+ [The {broom} package](https://www.youtube.com/watch?v=eM3Ha0kTAz4)

<!---------------------------------------------------------------------------->
<!-------------------------- MACHINE LEARNING -------------------------------->
<!---------------------------------------------------------------------------->

## Machine learning

#### TensorFlow
+ [Machine learning and TensorFlow](https://www.youtube.com/watch?v=atiYXm7JZv0) by Rstudio

#### Basics
+ [Intro to machine learning with {caret}](https://www.youtube.com/watch?v=z8PRU46I3NY)
+ [{caret} package webinar](https://www.youtube.com/watch?v=7Jbb2ItbTC4)
+ [Modeling with gbm, glmnet, and caret](https://www.youtube.com/watch?v=-nai4NBx5zI)
+ [xgboost with {caret}](https://www.youtube.com/watch?v=GuOw4W_A8VE)

<!---------------------------------------------------------------------------->
<!------------------------------ FRONT ENDS ---------------------------------->
<!---------------------------------------------------------------------------->

## Front ends

#### Rmarkdown
+ [Intro to bookdown](https://www.youtube.com/watch?v=dVqVscgwSpw)
+ [Using Spark with Rmarkdown](https://www.youtube.com/watch?v=GtVwHNxXVgQ)

#### Shiny
+ [Interactive graphics with Shiny](https://www.youtube.com/watch?v=1bCfympGLo8) by Rstudio
+ [Intro to flex dashboards](https://www.youtube.com/watch?v=O3CgrEwTg1k)
+ [Shiny gadgets](https://www.youtube.com/watch?v=ZMrJFKA-7RQ)

#### Websites
+ [Building a new Hugo site](https://www.youtube.com/watch?v=D4voy39ewb0) by Steph Locke

<!---------------------------------------------------------------------------->
<!------------------------------ BIG DATA ------------------------------------>
<!---------------------------------------------------------------------------->

## Big data

#### Databases
+ [Interacting with databases](https://www.youtube.com/watch?v=ywXZp7guvRE)

#### Spark
+ [Using Spark with Rmarkdown](https://www.youtube.com/watch?v=GtVwHNxXVgQ)
+ [Understanding sparklyr deployment modes](https://www.youtube.com/watch?v=NW5OPTKSkGY)
+ [Advanced features of sparklyr](https://www.youtube.com/watch?v=0KG0UCdleck)
+ [Extending Spark using sparklyr](https://www.youtube.com/watch?v=KIdxEu-JvXo)

#### Web data
+ [Importing web data pt 1](https://www.youtube.com/watch?v=zc0ayq-c0OM)
+ [Importing web data pt 2](https://www.youtube.com/watch?v=tCE9LPOQ9vg)

<!---------------------------------------------------------------------------->
<!------------------------------ ADVANCED R ---------------------------------->
<!---------------------------------------------------------------------------->

## Advanced R

#### Development

+ [Profiling tools for faster code](https://www.youtube.com/watch?v=LR8S2lrH_XM)
+ [Covr test coverage](https://www.youtube.com/watch?v=wP82XSFEiYs) by Rstudio

#### Programming

+ [The R6 class](https://www.youtube.com/watch?v=3GEFd8rZQgY)

